### ISSUE TITLE
Configuring plantumljar doesn't work, and needs documentation

### ISSUE THREAD

**Issue by kornysietsma** [baerrach/gatsby-remark-plantuml#10]
There is a syntax error in index.js at line 42:
`this.planumljar = path.resolve(pluginOptions.plantumljar)`
Should be `plantumljar` not `planumljar`

Also documentation for this would be good, I had to read the source to find it, and then have fun finding out why it doesn't work.

**Comment by baerrach** [comment]
Released v0.6.0
