### ISSUE TITLE
Allow adding additional params for plantuml

### ISSUE THREAD

**Issue by bharatrajagopalan** [baerrach/gatsby-remark-plantuml#16]
Hi

It would be good to have two params for adding custom params for java plantuml so that one can pass in all the plantuml arguments   are passed in either before or after the ```-jar plantuml.jar ``` argument
e.g. plantuml-java-opts, plantuml-opts

I am currently working around this issue by using the JAVA_TOOLS environment option which will pass it by default to every java command but it is nicer to configure this as part of the project config
e.g.

```export JAVA_TOOL_OPTIONS="-Dapple.laf.useScreenMenuBar=true -Dplantuml.include.path=${OMNICRON_WIKI_WORKSPACE}/src/plantuml/include:${OMNICRON_WIKI_WORKSPACE}/src/plantuml/:$HOME/git -DPLANTUML_LIMIT_SIZE=24384 -Xmx1024M"```

**Comment by baerrach** [comment]
I can see a need for the ${JAVA_OPTS} parameter.
But what additional plantuml opts do you need to specificy? This has the potential to break the plugin...

**Comment by baerrach** [comment]
Added in ea1dd65

**Comment by bharatrajagopalan** [comment]
Hi there

Sorry just saw this. I agree with your note that adding extra plantuml attrs could break this
. I see the way you have added it in with the warning which works for me. In most use cases it would be only the java opts that is used and not the plantuml opts. Thanks! This is really powerful
