### ISSUE TITLE
maxWidth does not work because style attribute overrides it

### ISSUE THREAD

**Issue by baerrach** [baerrach/gatsby-remark-plantuml#4]
See #1 

You can see from the generated svg for `max-width-option-overrides-svg-width-and-svg-height-but-viewbox-is-unaltered-1.html` that it has a `style` attribute

```
 style="width:1196px;height:526px;"
```

Plugin needs to remove any `width` or `height` from the `style` attribute

**Comment by ibm-omnicron** [comment]
Hi
For now i am working around this by setting the following in index.scss

//plantuml styling - override height with !important to ensure that aspect ratio is kept
svg {
    max-width:100% ;height:auto !important
}

**Comment by bharatrajagopalan** [comment]
Hi

I am currently working around this by adding the following in index.scss. This will work as long as plantuml is the only svg is being generated - that may not be always the case. 

//plantuml styling - override height with !important to ensure that aspect ratio is kept
svg {
    max-width:100% ;height:auto !important
}

**Comment by baerrach** [comment]
Fixed by #15
