### ISSUE TITLE
Support plantuml server local installation 

### ISSUE THREAD

**Issue by antessio** [baerrach/gatsby-remark-plantuml#8]
Running gatsby in a docker container makes the plantuml configuration not very easy. 

Since there's this nice docker container (https://github.com/plantuml/plantuml-server)  to run a local installation of plantuml server, would it be possible to add an extra configuration to convert the plantuml code using the URL http://localhost:8080/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

Or maybe even better a configuration to specify a plantuml server base URL so it can be used either a local installation or the public URL (http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000)

**Comment by baerrach** [comment]
Feel free to fork, or supply a pull request, if you want this feature.

I have it working as is and I dont have the capacity to write this myself.

**Comment by antessio** [comment]
Ok, thanks. I'm not very familiar with gatby plugins but maybe I'll try to supply a pull request.
