### ISSUE TITLE
Japanese characters are garbled

### ISSUE THREAD

**Issue by fni-pj** [baerrach/gatsby-remark-plantuml#9]
![コメント 2020-02-28 004712](https://user-images.githubusercontent.com/54523904/75459782-ea24da80-59c3-11ea-94d4-e7c5eedb124c.png)

```plantuml
@startuml
entity "オペレーター\noperators" as operators {
        * **operator_code**: char(10), AUTOINCREMENT
        --
        * **user_id**: bigserial [FK]
        * employee_number: integer, 共通社員番号
        * role: char, オペレーターの役職
        * type: char, L2L3振り分け
        is_leaving: boolean, default: false, 離席中かどうか
        notification_available_delay: boolean, default: true, 対応遅延時通知の ON/OFF
        notification_available_new: boolean, default: true, 新規入信通知の ON/OFF
        notification_available_response: boolean, default: true, 返信時通知の ON/OFF
        delay_notification_time: time, 遅延時通知時間
        max_acceptable_items: smallserial, default: 20, 受可上限値
        created_at: timestamp, default: CURRENT_TIMESTAMP
        updated_at: timestamp, default: CURRENT_TIMESTAMP
        deleted_at: timestamp, default: null
}
@enduml
```

**Comment by baerrach** [comment]
Just tried https://liveuml.com/ with this example.

It failed even worse!

![image](https://user-images.githubusercontent.com/723962/75500467-f426f780-5a1c-11ea-92a9-2e3845925960.png)

**Comment by baerrach** [comment]
http://www.plantuml.com/plantuml/uml/dPBHQnCn7CVV-rU4FMcvuPnlVTeOBGpNLchtf7AaTx_MG2vt9Bbf4M7NqY5Jg3ATR0eosGI7i_gY5NNzOz9qxNzXkkfnKpTnzn1-EVBvvFk5p0c9kGmzcW8cYQoZATNOLyrjrNodcjzKesVMcymFW6FfSp65i43n3jrBePzV6gNJl_xRZkz2Efr1pctCBroUkMYX-ULoSR6mKChciuLo34rFd-130TmcxfYia9hP44pHZTpLMubJu0NKhmFOBFGgm3E8C0aru1RIhO-ZrUsZtKEziNFqR5-tFoSmxbEOvB7GdmLLz5v__pACaeIi1p6nDBjqPV2eenhh-i6QYfx4nuYmAU0Lmcecik-RcLd8XIeEgSoWAgO2B3HwyLft3_hT0nKzLD5R5QsP8LOmNv8gSR0aFhFn2YOKLoZOBb1S_vjKyj0uTUTGzrwEefR--ccmrHWNVxLdQg1YuL8nb_kNdS6Tqzs3pG_3DstTskltTlvNp444FXDmkdtOUsgyPsK-hcwVk40IpoZDQWI_bHuFcninxE6xDdOS2EHn7YB14naaF4pfv44b0itEM4Ytd-jsfzzT7sqzrgkxiSVXW2MuDfQJUuN4Nf1W5vPB9VEKxV9YFdkzF9-_5fDXu9wJDCNXB9A5bARkf-Q0kQ57Vm00

**Comment by baerrach** [comment]
Fixed in 0.5.0.

Give it a try

**Comment by fni-pj** [comment]
Thunk you!

**Comment by baerrach** [comment]
すみません!
